### ISSUE TITLE
Build fail 

### ISSUE THREAD

**Issue by dosumis** [owlcollab/owltools#167]
Travis build looks like its passing, but I'm getting this when building locally:

[INFO] OWLTools-Core ...................................... FAILURE [02:29 min]

Suspect this is the relevant bit of the log:

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.094 sec <<< FAILURE! - in owltools.mooncat.RemoveDirectivesTest
testRemove(owltools.mooncat.RemoveDirectivesTest)  Time elapsed: 0.092 sec  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at owltools.mooncat.RemoveDirectivesTest.testRemove(RemoveDirectivesTest.java:63)

Building on a mac with the latest maven and 
java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
ackee:OWLTools-Parent davidos$

**Comment by cmungall** [comment]
This test is for the magical `logical-definition-view-relation` tag. This allows us to sneak in nesting to obo in limited circumstances.

Reasoning about the behavior of this tag is actually difficult. It takes as an argument a shorthand relation, so shorthands must be preserved for this to work through roundtripping. The tag itself must be preserved otherwise the axiom will end up in `owl-axioms` in the header.

It's strange this should fail now. It does point to potential issues when using this magical tag in production settings.

**Comment by cmungall** [comment]
OK, merge does behave as expected with this tag, the test was using the wrong API

still odd how travis didn't catch this
